import { useState } from 'react';
type Screen = 'route' | 'stop' | 'offline' | 'sync';
const stops = [{ n: 1, name: 'Highland Mart', district: 'Kandy', window: '05:30–06:00 AM', distance: '31.4 km' }, { n: 2, name: 'Green Valley Store', district: 'Peradeniya', window: '06:05–06:35 AM', distance: '6.2 km' }, { n: 3, name: 'Midlands Supermart', district: 'Gampola', window: '06:40–07:15 AM', distance: '8.9 km' }, { n: 4, name: 'North Central Mart', district: 'Kurunegala', window: '07:20–07:45 AM', distance: '22.7 km' }];
function Header({ title, sub, offline = false }: { title: string; sub: string; offline?: boolean }) { return <header><div className="topline"><span className="brand-dot">W</span><span>WAYPOINT DRIVER</span><span className={`connection ${offline ? 'bad' : ''}`}><i />{offline ? 'Offline' : 'Online'}</span></div><small>{sub}</small><h1>{title}</h1></header> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`card ${className}`}>{children}</div> }
function Route({ go }: { go: (s: Screen) => void }) { return <><Header title="Today's route" sub="Rohan Silva · WP-CAB-9241 · Trip 1" /><div className="hero-stats"><div><small>NEXT STOP</small><b>1 of 4</b></div><div><small>WINDOW</small><b>05:30–07:45</b></div><div><small>BRAND</small><b>Fresh</b></div></div><main><p className="section-label">Delivery sequence</p>{stops.map((s, i) => <Card className={i === 0 ? 'next' : ''} key={s.n}><div className="stop-top"><span className="number">{s.n}</span><div><b>{s.name}</b><small>{s.district} District · Fresh</small></div><strong>{s.distance}<small>away</small></strong></div><div className="window">◷ Window <b>{s.window}</b></div>{i === 0 && <button className="primary" onClick={() => go('stop')}>Navigate to stop <span>→</span></button>}</Card>)}<div className="safety">ⓘ Record delivery only when safely stopped. Do not use the app while driving.</div></main><Nav screen="route" go={go} /></> }
function Stop({ go }: { go: (s: Screen) => void }) { const [outcome, setOutcome] = useState('delivered'); return <><Header title="Midlands Supermart" sub="Stop 3 of 4 · WPF-2026-08741" /><div className="notice">! Shortfall pre-noted: 6 units of Anchor Milk missing.</div><main><Card><div className="detail"><b>Gampola District</b><span>06:40–07:15 AM</span></div><p className="section-label">What happened at this stop?</p>{[['delivered', 'Delivered', 'Partial · 6 units short', '✓'], ['attempted', 'Attempted', 'No one available', '!'], ['refused', 'Refused', 'Outlet refused delivery', '×']].map(x => <button className={`outcome ${outcome === x[0] ? `chosen ${x[0]}` : ''}`} key={x[0]} onClick={() => setOutcome(x[0])}><span>{x[3]}</span><b>{x[1]}</b><small>{x[2]}</small></button>)}{outcome === 'delivered' && <div className="proof"><b>Proof of delivery</b><input placeholder="Recipient name" /><input defaultValue="06:52 AM" /><div className="photo">⌾ Attach delivery photo</div></div>}<textarea placeholder="Notes (optional)" /><button className="primary full" onClick={() => go('offline')}>Confirm and record</button></Card></main><Nav screen="stop" go={go} /></> }
function Offline({ go }: { go: (s: Screen) => void }) { return <><Header title="Delivery saved" sub="Stop 1 · Highland Mart · WP-CAB-9241" offline /><div className="offline-alert"><b>No signal · Kandy corridor dead zone</b><span>1 delivery waiting to sync. Records are safe.</span></div><main><Card className="saved"><div className="saved-title"><span>▣</span><b>Delivery saved locally</b><em>SYNC PENDING</em></div><div className="data-grid"><div><small>Outlet</small><b>Highland Mart</b></div><div><small>Outcome</small><b className="green-text">✓ Delivered</b></div><div><small>Recorded at</small><b>07:22 AM</b></div><div><small>Status</small><b>Saved locally</b></div></div></Card><p className="section-label">Remaining stops · 3 of 4</p>{stops.slice(1).map(s => <Card className="compact" key={s.n}><span className="number">{s.n}</span><div><b>{s.name}</b><small>{s.district} · {s.window}</small></div></Card>)}<div className="safety">Live Board shows WP-CAB-9241 as <b>Offline</b> until signal returns.</div><button className="primary full" onClick={() => go('sync')}>Continue route <span>→</span></button></main><Nav screen="offline" go={go} /></> }
function Sync({ go }: { go: (s: Screen) => void }) { return <><Header title="End of day" sub="WP-CAB-9241 · Rohan Silva" /><main className="sync-main"><div className="sync-icon">✓</div><h2>All stops recorded</h2><p>All delivery records uploaded.</p><Card><div className="result"><span>Stops recorded</span><b>4 of 4</b></div><div className="result"><span>Data upload</span><b className="green-text">Synced</b></div><div className="result"><span>Delivered</span><b className="green-text">3</b></div><div className="result warning-result"><span>Attempted · no one available</span><b>1</b></div><div className="result"><span>Route completed at</span><b>07:42 AM</b></div></Card><button className="secondary full" onClick={() => go('route')}>Return to route</button></main><Nav screen="sync" go={go} /></> }
function Nav({ screen, go }: { screen: Screen; go: (s: Screen) => void }) { return <nav className="bottom-nav"><button className={screen === 'route' ? 'active' : ''} onClick={() => go('route')}>⌂<small>Route</small></button><button className={screen === 'stop' ? 'active' : ''} onClick={() => go('stop')}>＋<small>Deliver</small></button><button className={screen === 'offline' || screen === 'sync' ? 'active' : ''} onClick={() => go('offline')}>◉<small>Sync</small></button></nav> }
export default function App() { const [screen, setScreen] = useState<Screen>('route'); return <div className="phone-app">{screen === 'route' && <Route go={setScreen} />}{screen === 'stop' && <Stop go={setScreen} />}{screen === 'offline' && <Offline go={setScreen} />}{screen === 'sync' && <Sync go={setScreen} />}</div> }
