"""
Delivery workflow Pydantic schemas — Phase 6.

Covers:
  - Delivery outcome (driver records per stop)
  - Proof of Delivery (driver captures after delivery)
  - Shortfall (loader records before departure)
  - Receipt Confirmation (store manager confirms what arrived)
"""
from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, Field


# ── Delivery outcome ──────────────────────────────────────────────────────────

DeliveryOutcome = Literal["delivered", "attempted", "refused"]


class DeliveryCreate(BaseModel):
    """
    POST /api/v1/deliveries — driver records outcome for a trip stop.

    offline_operation_id is a client-generated UUID used as an idempotency key.
    The driver generates this on their device before going offline so that the
    same operation cannot be double-applied on sync.
    """
    trip_stop_id: str = Field(..., description="The trip stop being completed.")
    outcome: DeliveryOutcome
    recipient_name: str | None = Field(None, max_length=200)
    notes: str | None = Field(None, max_length=1000)
    delivered_at: datetime.datetime | None = Field(
        None,
        description="Driver's device time of delivery. Defaults to server time if omitted.",
    )
    # Idempotency key — must be a UUID generated by the client
    offline_operation_id: str | None = Field(
        None,
        description="Client-generated UUID for offline idempotency. Omit for online-only.",
    )


class DeliveryResponse(BaseModel):
    id: str
    trip_stop_id: str
    driver_id: str | None
    outcome: str
    recipient_name: str | None
    notes: str | None
    delivered_at: datetime.datetime | None
    offline_operation_id: str | None
    synced_at: datetime.datetime | None
    created_at: datetime.datetime


# ── Proof of Delivery ─────────────────────────────────────────────────────────

class ProofOfDeliveryCreate(BaseModel):
    """
    POST /api/v1/deliveries/{id}/pod — driver attaches proof to a delivery.

    photo_url and recipient_signature_url point to files already uploaded
    to Supabase Storage. The client uploads the file first, gets the URL,
    then submits this payload.
    """
    recipient_name: str = Field(..., min_length=1, max_length=200)
    photo_url: str | None = Field(None, description="Supabase Storage URL of delivery photo.")
    recipient_signature_url: str | None = Field(None, description="Supabase Storage URL of signature scan.")
    recorded_at: datetime.datetime = Field(
        ...,
        description="Driver's device timestamp when POD was captured.",
    )


class ProofOfDeliveryResponse(BaseModel):
    id: str
    delivery_id: str
    recipient_name: str
    photo_url: str | None
    recipient_signature_url: str | None
    recorded_at: datetime.datetime
    created_at: datetime.datetime


# ── Shortfall ─────────────────────────────────────────────────────────────────

ShortfallIssueType = Literal["missing", "damaged", "wrong_item"]


class ShortfallCreate(BaseModel):
    """
    POST /api/v1/trips/{id}/stops/{stop_id}/shortfall
    Loader records a shortfall before the vehicle departs.
    """
    issue_type: ShortfallIssueType
    sku: str = Field(..., min_length=1, max_length=50)
    description: str = Field(..., min_length=1, max_length=200)
    expected_quantity: int = Field(..., gt=0)
    actual_quantity: int = Field(..., ge=0)
    photo_url: str | None = Field(None, description="Supabase Storage URL of shortfall photo.")
    notes: str | None = Field(None, max_length=500)


class ShortfallResponse(BaseModel):
    id: str
    trip_stop_id: str
    issue_type: str
    sku: str
    description: str
    expected_quantity: int
    actual_quantity: int
    photo_url: str | None
    notes: str | None
    recorded_by: str | None
    created_at: datetime.datetime


# ── Receipt Confirmation ──────────────────────────────────────────────────────

class ReceiptConfirmationCreate(BaseModel):
    """
    POST /api/v1/deliveries/{id}/confirm — store manager confirms receipt.

    items_received is a dict of {sku: quantity_received}.
    """
    items_received: dict[str, int] = Field(
        ...,
        description="Map of SKU → quantity actually received by the store.",
    )
    issues_noted: str | None = Field(
        None,
        max_length=1000,
        description="Free-text issues noticed upon receipt.",
    )


class ReceiptConfirmationResponse(BaseModel):
    id: str
    delivery_id: str
    order_id: str
    confirmed_by: str | None
    items_received: dict
    issues_noted: str | None
    confirmed_at: datetime.datetime
    created_at: datetime.datetime
