"""
Sync schemas — Phase 7 offline/online sync engine.

Contract design principles:
  - Driver sends a BATCH of operations (could be 1..N queued since last connection).
  - Each operation carries its own `operation_id` (client-generated UUID) — that is
    the idempotency key.  Duplicate submissions of the same operation_id are safe.
  - Server processes each operation independently and returns a per-op result list.
  - The batch never fails atomically — partial success is valid. The driver retries
    only the ops whose result status is not 'applied' or 'duplicate'.

Operation types supported in Phase 7:
  - complete_delivery   -> creates a deliveries row
  - record_pod          -> creates a proof_of_delivery row
  - record_shortfall    -> creates a shortfall row
"""
from __future__ import annotations

import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

# ── Supported operation names (matches sync_events.operation CHECK constraint) ─

SyncOperationName = Literal[
    "complete_delivery",
    "record_pod",
    "record_shortfall",
]

# ── Status returned per operation after processing ────────────────────────────

SyncResultStatus = Literal[
    "applied",      # successfully applied — entity created
    "duplicate",    # operation_id already seen — idempotent no-op
    "failed",       # validation or conflict error — see error_detail
]


# ── Single operation in the batch ────────────────────────────────────────────

class SyncOperation(BaseModel):
    """
    One offline operation queued by the driver app.

    `operation_id` is a UUID generated by the client *before* the network was
    lost.  It ties this sync submission to the sync_events audit row and to the
    deliveries.offline_operation_id column.

    `payload` is operation-specific.  The server validates it after determining
    the operation type.

    complete_delivery payload fields:
        trip_stop_id    : str   (UUID)
        outcome         : "delivered" | "attempted" | "refused"
        recipient_name  : str | None
        notes           : str | None
        delivered_at    : ISO-8601 datetime string | None

    record_pod payload fields:
        delivery_id             : str  (UUID)
        recipient_name          : str
        photo_url               : str | None
        recipient_signature_url : str | None
        recorded_at             : ISO-8601 datetime string

    record_shortfall payload fields:
        trip_stop_id      : str (UUID)
        issue_type        : "missing" | "damaged" | "wrong_item"
        sku               : str
        description       : str
        expected_quantity : int
        actual_quantity   : int
        photo_url         : str | None
        notes             : str | None
    """
    operation_id: str = Field(
        ...,
        description="Client-generated UUID.  The idempotency key for this operation.",
        min_length=1,
        max_length=128,
    )
    operation: SyncOperationName = Field(
        ...,
        description="Type of operation to apply.",
    )
    device_id: str | None = Field(
        None,
        description="Optional client device identifier — stored in sync_events for audit.",
        max_length=128,
    )
    occurred_at: datetime.datetime | None = Field(
        None,
        description=(
            "Driver's device timestamp when the action actually happened. "
            "Stored for audit; server timestamps are also recorded."
        ),
    )
    payload: dict[str, Any] = Field(
        ...,
        description="Operation-specific data.  See class docstring for field details.",
    )


# ── Batch request (driver POSTs this when connectivity is restored) ───────────

class SyncBatchRequest(BaseModel):
    """
    POST /api/v1/sync — driver sends all queued offline operations in one call.

    Operations are processed in the order they appear in the list.
    Each is handled independently; one failure does not block the rest.
    """
    operations: list[SyncOperation] = Field(
        ...,
        min_length=1,
        description="Ordered list of offline operations to apply.",
    )


# ── Per-operation result ──────────────────────────────────────────────────────

class SyncOperationResult(BaseModel):
    """
    Result for one operation in the batch.

    `entity_id` is the UUID of the created/found entity (if applicable).
    On failure it may be None.
    """
    operation_id: str
    status: SyncResultStatus
    entity_id: str | None = Field(
        None,
        description="ID of the affected entity (delivery, POD, shortfall row).",
    )
    error_detail: str | None = Field(
        None,
        description="Human-readable reason for failure.  Only set when status='failed'.",
    )


# ── Batch response ────────────────────────────────────────────────────────────

class SyncBatchResponse(BaseModel):
    """
    Response to POST /api/v1/sync.

    `results` has exactly one entry per submitted operation, in the same order.
    The driver should dequeue any operations whose result status is 'applied'
    or 'duplicate'.  Operations with status 'failed' should be flagged for
    manual review — retrying them without payload changes will likely fail again.
    """
    results: list[SyncOperationResult]
    applied_count: int = Field(description="Number of operations successfully applied.")
    duplicate_count: int = Field(description="Number of already-seen operation IDs (safe no-ops).")
    failed_count: int = Field(description="Number of operations that could not be applied.")


# ── Driver sync-status query response ────────────────────────────────────────

class SyncEventResponse(BaseModel):
    """
    One entry in GET /api/v1/sync/status — the driver's operation log.
    """
    id: str
    operation_id: str
    device_id: str | None
    entity_type: str
    entity_id: str
    operation: str
    status: str
    error_detail: str | None
    received_at: datetime.datetime
    applied_at: datetime.datetime | None


class SyncStatusResponse(BaseModel):
    """
    Response to GET /api/v1/sync/status — returns all sync events for the
    authenticated driver (newest first).
    """
    events: list[SyncEventResponse]
    total: int
